version: "3"
services:
    mongo:
        image: mongo
        volumes:
            - /database/data
        ports:
            - "27017:27017"
    frontend:
        container_name: awesome_web
        build:
            context: ./front
            dockerfile: Dockerfile
        image: hiro/awesome_web
        ports:
            - "3000:3000"
        restart: always
    backend:
        container_name: awesome_server
        build:
            context: ./back
            dockerfile: Dockerfile
        image: hiro/awesome_server
        ports:
            - "8085:8085"
        restart: always
        links:
            - mongo
