version: "3"
services:
    frontend:
        container_name: awesome_web
        build:
            context: ./
            dockerfile: Dockerfile
        image: hiro/awesome_web
        ports:
            - "3000:3000"
        restart: always